[package]
name = "torrent"
version = "0.1.0"
authors = ["stephen <26316200+slo1@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "bencode"
path = "src/bencode.rs"

[[bin]]
name = "bt"
path = "src/main.rs"

[dependencies]
